config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  resources :machine_records do
    resources :comments
    resources :entries
    resources :preventative_maintenances
  end

  resources :comments

  # devise_for :users
  # devise_for :users do
  #   delete '/users/sign_out' => 'devise/sessions#destroy'
  # end

  Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
    end

    resources :users, only: [:index, :show]

  root 'machine_records#index'

end

app/models/machine_record.rb
class MachineRecord < ApplicationRecord
  has_many  :comments, dependent: :destroy
  has_many  :preventative_maintenances, dependent: :destroy
  has_many  :entries, dependent: :destroy
  belongs_to :user

  # accepts_nested_attributes_for :comments, :preventative_maintenances, :entries

  validates :name, presence: true
  validates :serial_number, presence: true
  # validates_associated :comments, :preventative_maintenances, :entries

  def pms?
    self.preventative_maintenances.any?
  end

  def recent_pms
    if self.pms?
      self.preventative_maintenances.limit(5).order('date desc')
    end
  end

  def last_pm_date
    if self.pms?
      last_pm_date = self.preventative_maintenances.order('date DESC').first.date
      last_pm_date = last_pm_date.strftime('%B %e, %Y')
    else
      "N/A"
    end
  end

  def last_pm_date_short
    if self.pms?
      last_pm_date = self.preventative_maintenances.order('date DESC').first.date
      last_pm_date_short = last_pm_date.strftime('%D')
    else
      "n/a"
    end
  end

  def total_hours
    entries = self.entries.all.to_a
    sum = entries.reduce(0) { |sum, obj| sum + obj.hours.to_f }
    return sum.round(2)
  end

  def entries?
    self.entries.any?
  end

  def recent_entries
    self.entries.limit(5).order('id desc')
  end

end

app/controllers/machine_records_controller.rb
class MachineRecordsController < ApplicationController
  before_action :set_machine_record, only: [:show, :edit, :update, :destroy]

  # GET /machine_records
  # GET /machine_records.json
  def index
    if current_user.admin?
      @machine_records = MachineRecord.all
    else
      @machine_records = MachineRecord.where(:user_id => current_user.id)
    end
  end

  # GET /machine_records/1
  # GET /machine_records/1.json
  def show
    @machine_record = MachineRecord.find(params[:id])

  end

  # GET /machine_records/new
  def new
    @machine_record = MachineRecord.new
  end

  # GET /machine_records/1/edit
  def edit
  end

  # POST /machine_records
  # POST /machine_records.json
  def create
    @machine_record = MachineRecord.new(machine_record_params)
    @machine_record.user = current_user

    respond_to do |format|
      if @machine_record.save
        format.html { redirect_to @machine_record, notice: 'Machine record was successfully created.' }
        format.json { render :show, status: :created, location: @machine_record }
      else
        format.html { render :new, alert: 'There was a problem creating the machine record.' }
        format.json { render json: @machine_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machine_records/1
  # PATCH/PUT /machine_records/1.json
  def update
    respond_to do |format|
      if @machine_record.update(machine_record_params)
        format.html { redirect_to @machine_record, notice: 'Machine record was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine_record }
      else
        format.html { render :edit }
        format.json { render json: @machine_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_records/1
  # DELETE /machine_records/1.json
  def destroy
    @machine_record.destroy
    respond_to do |format|
      format.html { redirect_to machine_records_url, notice: 'Machine record was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine_record
      @machine_record = MachineRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def machine_record_params
      params.require(:machine_record).permit(:name, :serial_number, :machine_number, :user_id)
    end
end

app/helpers/machine_records_helper.rb
module MachineRecordsHelper
end

app/views/machine_records/_form.html.erb
<%= form_with(model: machine_record, local: true) do |form| %>
  <% if machine_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine_record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% machine_record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name %>
    <%= form.label :name, { class: 'control-label'} %>
    <i class="bar"></i>
  </div>

  <div class="form-group">
    <%= form.text_field :machine_number %>
    <%= form.label :machine_number, { class: 'control-label' } %>
    <i class="bar"></i>
  </div>

  <div class="form-group">
    <%= form.text_field :serial_number %>
    <%= form.label :serial_number, { class: 'control-label' } %>
    <i class="bar"></i>
  </div>

  <div class="button-container">
    <%= form.button "<span>Submit</span>".html_safe, { class: 'button' } %>
  </div>
<% end %>

app/views/machine_records/edit.html.erb
<div class="container top-card">
  <div class="form">
    <h1>Editing Machine Record</h1>
    <%= render 'form', machine_record: @machine_record %>
  </div>
  <%= link_to :back, class: "icon" do %>
    <i class="fa fa-arrow-left"> Back</i>
  <% end %>
</div>

app/views/machine_records/index.html.erb
<div class="header">
  <div class="header-left">
    <% if current_user.admin? %>
      <p class="font-size-10 font-italic">Admin</p>
    <% end %>
    <h1 class="header-title"><%= current_user.name %></h1>
    <div class="header-detail">
      <p class="header-item"><%= current_user.company %></p>
    </div>
  </div>
  <div class="header-right">
    <h1 class="header-title"><%= current_user.machine_records.all.count %></h1>
    <div class="header-detail">
      <p class="header-item"><%= "Machine".pluralize(current_user.machine_records.all.count) %></p>
    </div>
  </div>
</div>
<div class="container">
  <h2>Machine Records</h2>
  <div class="index">
    <div class="col col-head">
      Name
    </div>
    <div class="col col-head">
      Serial
    </div>
    <div class="col col-head">
      Last PM
    </div>
    <div class="col col-control col-head">
      <% if current_user.admin? %>
        <div class="controls">

        </div>
        <div class="controls">

        </div>
      <% else %>
        <div class="controls"></div>
        <div class="controls"></div>
      <% end %>
    </div>

    <% if @machine_records.any? %>
      <% @machine_records.each do |machine_record| %>
        <div class="col">
          <%= link_to machine_record.name, machine_record %>
        </div>
        <div class="col">
          <%= machine_record.serial_number %>
        </div>
        <div class="col">
          <%= machine_record.last_pm_date_short %>
        </div>
        <div class="col-control">
          <% if current_user.admin? %>
            <div class="controls">
              <%= link_to edit_machine_record_path(machine_record), class: "icon icon-edit" do %>
                <i class="fa fa-edit"></i>
              <% end %>
            </div>
            <div class="controls">
              <%= link_to machine_record, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon icon-delete" do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </div>
          <% else %>
            <div class="controls"></div>
            <div class="controls"></div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p>No machine records.</p>
    <% end %>
  </div>
</div>

app/views/machine_records/new.html.erb
<div class="container top-card">
  <div class="form">
    <h1>New Machine Record</h1>
    <%= render 'form', machine_record: @machine_record %>
  </div>
  <%= link_to :back, class: "icon" do %>
    <i class="fa fa-arrow-left"> Back</i>
  <% end %>
</div>

app/views/machine_records/show.html.erb
<div class="header">
  <div class="header-left">
    <h1 class="header-title"><%= @machine_record.name %></h1>
    <div class="header-detail">
      <p class="header-item">Serial #<%= @machine_record.serial_number %></p>
      <p class="header-item">Machine #<%= @machine_record.machine_number %></p>
      <p class="header-item font-italic font-size-10 margin-top-5">Last PM: <%= @machine_record.last_pm_date %></p>
    </div>
    <% if current_user.admin? %>
      <div class="header-detail padding-top-5">Owned by <%= @machine_record.user.name %></div>
      <div class="header-detail"><%= mail_to @machine_record.user.email, @machine_record.user.email, subject: "#{@machine_record.name} - ##{@machine_record.machine_number}" %></div>
      <div class="header-detail padding-y-5">Work: <%= link_to @machine_record.user.work_phone, "tel:#{@machine_record.user.work_phone}" %></div>
      <div class="header-detail padding-y-5">Cell: <%= link_to @machine_record.user.cell_phone, "tel:#{@machine_record.user.cell_phone}" %></div>
      <div class="header-detail header-controls">
        <%= link_to edit_machine_record_path(@machine_record), class: "icon icon-edit header-icon" do %>
          <i class="fa fa-edit"> EDIT </i>
        <% end %>
        <%= link_to @machine_record, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon icon-delete header-icon" do %>
          <i class="fa fa-trash"> DELETE </i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="header-right">
    <h1 class="header-title"><%= @machine_record.total_hours %></h1>
    <div class="header-detail">
      <p class=header-item><%= "Hour".pluralize(@machine_record.total_hours) %> Total</p>
    </div>
  </div>

</div>
<div class="container">
  <% if @machine_record.entries? %>
  <h3>Latest Entries</h3>
  <div class="entry entry-header">
    <div class="hours">
      <strong>Hours</strong>
    </div>
    <div class="submitted">
      <strong>Submitted</strong>
    </div>
  </div>
  <%= render @machine_record.recent_entries %>
  <% end %>
  <div class="entry">
    <%= render 'entries/form' %>
  </div>

  <% if @machine_record.pms? %>
  <h3>Recent Maintenance</h3>
  <div class="entry entry-header">
    <div class="hours">
      <strong>Description</strong>
    </div>
    <div class="submitted">
      <strong>Performed</strong>
    </div>
  </div>
  <%= render @machine_record.recent_pms %>
  <% end %>
  <div class="entry">
    <%= render 'preventative_maintenances/form' %>
  </div>

  <div class="comments">
    <h3>Comments</h3>
    <% if @machine_record.comments.any? %>
      <%= render @machine_record.comments.order('created_at DESC') %>
    <% else %>
      <p>No one has made a comment yet.</p><br />
    <% end %>
    <%= render 'comments/form' %>
  </div>










  <%= link_to machine_records_path, class: "icon" do %>
    <i class="fa fa-arrow-left"> Back</i>
  <% end %>
</div>