config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  resources :machine_records do
    resources :comments
    resources :entries
    resources :preventative_maintenances
  end

  resources :comments

  # devise_for :users
  # devise_for :users do
  #   delete '/users/sign_out' => 'devise/sessions#destroy'
  # end

  Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
    end

    resources :users, only: [:index, :show]

  root 'machine_records#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RishApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/1ce894217f.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% flash.each do |type, message| %>
      <% if type.upcase == "NOTICE" %>
        <div class="flash">
          <div class="flash-success">
            <%= message %>
          </div>
        </div>
      <% end %>
      <% if type.upcase == "ALERT" %>
        <div class="flash">
          <div class="flash-alert">
            <%= message %>
          </div>
        </div>
      <% end %>
      <% if type.upcase == "INFO" %>
        <div class="flash">
          <div class="flash-info">
            <%= message %>
          </div>
        </div>
      <% end %>
    <% end %>

    <nav class="navbar">
        <%= link_to root_path, class: "icon nav-icon" do %>
          <i class="fa fa-home"></i>
        <% end %>
      <div class="nav-session">
        <% if user_signed_in? %>
          <%= link_to edit_user_registration_path, class: "icon nav-icon" do %>
            <i class="fa fa-user"></i>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: "icon nav-icon" do %>
            <i class=" fa fa-sign-out-alt"></i>
          <% end %>
        <% else %>
          <%= link_to new_user_registration_path, class: "icon nav-icon" do %>
            <i class="fa fa-user-plus"></i>
          <% end %>
          <%= link_to new_user_session_path, class: "icon nav-icon" do %>
            <i class=" fa fa-sign-in-alt"></i>
          <% end %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
    <% if user_signed_in? %>
      <div class="fab-container">
        <div class="fab fab-icon-holder">
          <i class="fas fa-plus"></i>
        </div>
        <ul class="fab-options">
          <%= link_to new_machine_record_path do %>
          <li>
            <span class="fab-label">New Machine Record</span>
            <div class="fab-icon-holder">
              <i class="fas fa-truck-monster"></i>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    <% end %>

  </body>

</html>